import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import nftimg from "../public/image-equilibrium.jpg"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex items-center justify-center bg-slate-900 w-screen h-screen  text-white '>
        <section className=' bg-slate-800 max-h-lg max-w-xs  p-5 rounded-lg '>
          <div className='m-auto '>
            <div>
              <Image className='max- m-auto  rounded-lg pb-8' src={nftimg} alt='NFT Equilibrium'/>
            </div>
            <div>
              <h1>Equilibrium #3429</h1>
              <p>Our Equilibrium collection promotes balance and calm.</p>
            </div>
            <div className='flex justify-between'>
              <h1>ICONS</h1>
              <h1>TIME LEFT</h1>
            </div>
            <div className=" ">
              <h1>Creator</h1>
            </div> 
          </div>
        </section>
      </main>
    </>
  )
}
